
# NumPy Temelleri (DL Odaklı) — Okunaklı Versiyon

Bu defter, derin öğrenme için gereken NumPy temellerini **okunaklı** çıktılar ile anlatır.  
Her bölümde şu soruları cevaplıyoruz:
- **Bu fonksiyon ne işe yarar?**
- **Girdi → Çıktı nedir?**
- **Ne değişti?**

## 0) Kurulum

In [12]:

import numpy as np
print("NumPy sürümü:", np.__version__)


NumPy sürümü: 1.26.4



## 1) Array Oluşturma

**Ne işe yarar?** Tensörleri (çok boyutlu diziler) inşa ederiz. Sık kullanılan array oluşturma yöntemleri:
- `np.array`, `np.arange`, `np.linspace`
- `np.zeros`, `np.ones`, `np.full`
- `np.random.rand`, `np.random.randn`, `np.random.randint` (rastgele)

In [13]:

a = np.array([1, 2, 3])                      # Python list -> NumPy array
b = np.arange(1, 6)                           # 1..5 (tam sayılar)
c = np.linspace(0, 1, 5)                      # [0.00, 0.25, 0.50, 0.75, 1.00]
z = np.zeros((2, 3))                          # 2x3 sıfırlar
o = np.ones((2, 3))                           # 2x3 birler
r = np.random.randint(1, 10, size=(3, 3))     # 1..9 arası 3x3 rastgele

print("a:", a)
print("b:", b)
print("c:", c)
print("zeros (2x3):\n", z)
print("ones  (2x3):\n", o)
print("randint (3x3):\n", r)


a: [1 2 3]
b: [1 2 3 4 5]
c: [0.   0.25 0.5  0.75 1.  ]
zeros (2x3):
 [[0. 0. 0.]
 [0. 0. 0.]]
ones  (2x3):
 [[1. 1. 1.]
 [1. 1. 1.]]
randint (3x3):
 [[9 4 6]
 [5 9 6]
 [8 4 9]]



## 2) Şekil ve Boyut — `shape`, `reshape`, `ravel`, `flatten`, `transpose`

**Ne işe yarar?** Aynı veriyi farklı boyutlarda düzenlemek, DL’de batch/kanal/uzamsal eksenleri ayarlamak.
- `shape/ndim/size`: temel özellikler
- `reshape`: boyut değiştirir (mümkünse kopya yapmadan)
- `ravel`: çoğunlukla *view* (orijinale bağlı) — kopya oluşturmaz
- `flatten`: *kopya* oluşturur
- `T`/`transpose`: eksenleri çevirir
- `np.newaxis`/`None` ve `np.expand_dims`: yeni eksen ekler

In [14]:

x = np.arange(12)           # 0..11
X = x.reshape(3, 4)         # (3,4) şekline
x_view = X.ravel()          # görünüm (view) -> çoğu durumda kopya yok
x_copy = X.flatten()        # kopya
X_T = X.T                   # transpose

print("x:", x)
print("X (3x4):\n", X)
print("X_T (4x3):\n", X_T)
print("x_view ilk 5:", x_view[:5], "| view mi? ->", "Evet" if x_view.base is not None else "Hayır")
print("x_copy ilk 5:", x_copy[:5], "| kopya mı? ->", "Evet" if x_copy.base is None else "Hayır")

# View davranışı gözlem:
x_view[0] = 999   # view'ı değiştirince X etkilenir
print("\n[Değişiklik] x_view[0] = 999 yaptık")
print("X (etkilendi mi?):\n", X)
# Kopya etkilenmez
x_copy[1] = 777
print("\n[Değişiklik] x_copy[1] = 777 (kopya), X etkilenmez")
print("x_copy:", x_copy[:5])
print("X:\n", X)


x: [ 0  1  2  3  4  5  6  7  8  9 10 11]
X (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
X_T (4x3):
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
x_view ilk 5: [0 1 2 3 4] | view mi? -> Evet
x_copy ilk 5: [0 1 2 3 4] | kopya mı? -> Evet

[Değişiklik] x_view[0] = 999 yaptık
X (etkilendi mi?):
 [[999   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]

[Değişiklik] x_copy[1] = 777 (kopya), X etkilenmez
x_copy: [  0 777   2   3   4]
X:
 [[999   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]



## 3) İndeksleme & Dilimleme & Maskeler

**Ne işe yarar?** Veri altkümeleri seçme, koşullu filtreleme, mini-batch çıkarma.
- Basit dilim: `A[1:4]`, adımlı: `A[::2]`
- 2D: `A[i, j]`, `A[i, :]`, `A[:, j]`
- Boolean mask: `A[A>0]`
- Fancy index: `A[[0,2], :]`

In [15]:

A = np.arange(1, 10).reshape(3, 3)
print("A:\n", A)

print("\n2. satır:", A[1, :])
print("3. sütun:", A[:, 2])

mask = A > 5
print("\nMask (A > 5):\n", mask)
print("Seçili değerler:", A[mask])

fancy = A[[0, 2], :]  # 1. ve 3. satırlar
print("\nFancy index (satır 0 ve 2):\n", fancy)


A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

2. satır: [4 5 6]
3. sütun: [3 6 9]

Mask (A > 5):
 [[False False False]
 [False False  True]
 [ True  True  True]]
Seçili değerler: [6 7 8 9]

Fancy index (satır 0 ve 2):
 [[1 2 3]
 [7 8 9]]



## 4) Broadcasting — Boyutları Otomatik Eşleme

**Ne işe yarar?** Manuel döngü yazmadan farklı boyutlu tensörleri birlikte işlemek.
- `(N, 1)` + `(1, M)` → `(N, M)`
- Bias ekleme, ölçekleme, normalizasyon vb.


In [16]:

u = np.array([1, 2, 3])[:, None]     # (3,1)
v = np.array([10, 20, 30])[None, :]  # (1,3)

print("u shape:", u.shape, "\n", u)
print("v shape:", v.shape, "\n", v)

sum_uv = u + v    # (3,3)
mul_uv = u * v    # (3,3)

print("\nToplam (u+v):\n", sum_uv)
print("\nÇarpım (u*v):\n", mul_uv)
print("\nNe değişti? -> Boyutlar otomatik yayıldı (broadcast). Çıktı şekli:", sum_uv.shape)


u shape: (3, 1) 
 [[1]
 [2]
 [3]]
v shape: (1, 3) 
 [[10 20 30]]

Toplam (u+v):
 [[11 21 31]
 [12 22 32]
 [13 23 33]]

Çarpım (u*v):
 [[10 20 30]
 [20 40 60]
 [30 60 90]]

Ne değişti? -> Boyutlar otomatik yayıldı (broadcast). Çıktı şekli: (3, 3)



## 5) Özet İstatistikler — `mean/median/std/var/min/max` + `percentile/quantile`

**Ne işe yarar?** Dağılımı anlamak, normalizasyon kararları almak.


In [17]:

data = np.array([12, 15, 20, 18, 16, 22, 25, 100])  # uç değer (100) ekledik
print("Veri:", data)
print("Ortalama:", np.mean(data))            # Aritmetik ortalama
print("Medyan:", np.median(data))            # Ortanca
print("Standart sapma:", np.std(data))
print("Varyans:", np.var(data))
print("Maksimum:", np.max(data))
print("Minimum:", np.min(data))

# Yüzdelikler: belirli bir yüzdelik altındaki değer eşiği
print("\n%25 yüzdelik:", np.percentile(data, 25))
print("%50 yüzdelik (medyan):", np.percentile(data, 50))
print("%75 yüzdelik:", np.percentile(data, 75))

# Quantile: 0..1 aralığında eşdeğer gösterim
print("0.25 quantile:", np.quantile(data, 0.25))
print("0.75 quantile:", np.quantile(data, 0.75))


Veri: [ 12  15  20  18  16  22  25 100]
Ortalama: 28.5
Medyan: 19.0
Standart sapma: 27.294688127912362
Varyans: 745.0
Maksimum: 100
Minimum: 12

%25 yüzdelik: 15.75
%50 yüzdelik (medyan): 19.0
%75 yüzdelik: 22.75
0.25 quantile: 15.75
0.75 quantile: 22.75



## 6) Lineer Cebir — `@/dot/matmul`, `det`, `inv`, `norm`

**Ne işe yarar?** DL’de en kritik operasyonlar: matris/vektör çarpımı, normlar, bazı analizler.


In [18]:

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("A:\n", A)
print("B:\n", B)

prod = A @ B               # matris çarpımı
print("\nA @ B:\n", prod)

detA = np.linalg.det(A)
invA = np.linalg.inv(A)
print("\nDet(A):", detA)
print("Inv(A):\n", invA)

# Norm örneği (L2 normu)
v = np.array([3.0, 4.0])
print("\nVektör v:", v, " | L2 normu:", np.linalg.norm(v))


A:
 [[1 2]
 [3 4]]
B:
 [[5 6]
 [7 8]]

A @ B:
 [[19 22]
 [43 50]]

Det(A): -2.0000000000000004
Inv(A):
 [[-2.   1. ]
 [ 1.5 -0.5]]

Vektör v: [3. 4.]  | L2 normu: 5.0



## 7) Birleştirme & Bölme — `stack/vstack/hstack`, `split/vsplit/hsplit`

**Ne işe yarar?** Batch oluşturma, veri/etiket birleştirme veya ayırma.


In [19]:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

stacked = np.stack((a, b), axis=0)  # yeni eksen
v = np.vstack((a, b))               # dikey birleştirme
c = np.array([[1,2,3],[7,8,9]])
d = np.array([[4,5,6],[10,11,12]])
h = np.hstack((c, d))               # yatay birleştirme

print("stacked (yeni eksen):\n", stacked)
print("\nvstack:\n", v)
print("\nhstack:\n", h)

arr = np.arange(10)
pieces = np.split(arr, 5)
print("\narr:", arr)
print("5 parçaya böl:", pieces)

M = np.arange(16).reshape(4,4)
print("\nM:\n", M)
v1, v2 = np.vsplit(M, 2)
h1, h2 = np.hsplit(M, 2)
print("\nDikey bölümler:\n", v1, "\n\n", v2)
print("\nYatay bölümler:\n", h1, "\n\n", h2)


stacked (yeni eksen):
 [[1 2 3]
 [4 5 6]]

vstack:
 [[1 2 3]
 [4 5 6]]

hstack:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

arr: [0 1 2 3 4 5 6 7 8 9]
5 parçaya böl: [array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

M:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Dikey bölümler:
 [[0 1 2 3]
 [4 5 6 7]] 

 [[ 8  9 10 11]
 [12 13 14 15]]

Yatay bölümler:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]



## 8) İndeks Bulma — `where`, `argwhere`, `nonzero`

**Ne işe yarar?** Koşulu sağlayan elemanları ve **konumlarını** bulmak.
- `np.where(cond)` → indeks tuple’ı
- `np.argwhere(cond)` → `[i, j]` koordinatları
- `np.nonzero(A)` → sıfır olmayanların indeksleri


In [20]:

A = np.array([[0,1,0],
              [2,0,3],
              [0,4,0]])
print("A:\n", A)

w = np.where(A > 0)
print("\nnp.where(A>0) çıktı tipleri:", type(w), " | uzunluk:", len(w))
print("Satır indeksleri:", w[0])
print("Sütun indeksleri:", w[1])

arg = np.argwhere(A > 0)
print("\nnp.argwhere(A>0):\n", arg)

nz = np.nonzero(A)
print("\nnp.nonzero(A):", nz)
print("nonzero koordinatları:\n", np.array(nz).T)


A:
 [[0 1 0]
 [2 0 3]
 [0 4 0]]

np.where(A>0) çıktı tipleri: <class 'tuple'>  | uzunluk: 2
Satır indeksleri: [0 1 1 2]
Sütun indeksleri: [1 0 2 1]

np.argwhere(A>0):
 [[0 1]
 [1 0]
 [1 2]
 [2 1]]

np.nonzero(A): (array([0, 1, 1, 2], dtype=int64), array([1, 0, 2, 1], dtype=int64))
nonzero koordinatları:
 [[0 1]
 [1 0]
 [1 2]
 [2 1]]



## 9) Dosya I/O — `savetxt/loadtxt`, `save/load`, `savez(_compressed)`

**Ne işe yarar?** Ara sonuçları, tensörleri, küçük veri parçalarını diske kaydet/oku.


In [21]:

from pathlib import Path
Path("files").mkdir(exist_ok=True)

arr = np.arange(1, 11).reshape(2, 5)

# TXT olarak kaydet/oku
np.savetxt("files/veri.txt", arr, fmt="%d")
txt_back = np.loadtxt("files/veri.txt", dtype=int)

# NPY (binary tek array) kaydet/oku
np.save("files/veri.npy", arr)
npy_back = np.load("files/veri.npy")

# NPZ (çoklu array) kaydet/oku
a = np.arange(1, 6)
b = np.arange(10, 15)
np.savez("files/veriler.npz", array1=a, array2=b)
np.savez_compressed("files/veriler_compressed.npz", array1=a, array2=b)
z_load = np.load("files/veriler.npz")
zc_load = np.load("files/veriler_compressed.npz")

print("TXT geri yükleme:\n", txt_back)
print("\nNPY geri yükleme:\n", npy_back)
print("\nNPZ içerikleri (array1):", z_load["array1"])
print("NPZ (compressed) içerikleri (array2):", zc_load["array2"])


TXT geri yükleme:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

NPY geri yükleme:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

NPZ içerikleri (array1): [1 2 3 4 5]
NPZ (compressed) içerikleri (array2): [10 11 12 13 14]



## 10) İleri İstatistik — `percentile/quantile`, `cov`, `corrcoef`

**Ne işe yarar?**
- **Percentile/Quantile:** belirli yüzdelik altındaki değer eşiği (dağılım/kuyruk analizi)
- **Kovaryans (`np.cov`)**: iki değişken birlikte nasıl değişiyor
- **Korelasyon (`np.corrcoef`)**: -1..1 arasında ilişki gücü (normalize)


In [22]:

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])  # x ile tam doğrusal (y=2x)

print("x:", x)
print("y:", y)

print("\n%25 yüzdelik (x):", np.percentile(x, 25))
print("0.75 quantile (x):", np.quantile(x, 0.75))

cov = np.cov(x, y)
corr = np.corrcoef(x, y)
print("\nKovaryans matrisi:\n", cov)
print("\nKorelasyon matrisi:\n", corr)
print("\nNe değişti? -> Kovaryans mutlak ölçekten etkilenir; korelasyon -1..1 arası normalize değerdir (burada 1).")


x: [1 2 3 4 5]
y: [ 2  4  6  8 10]

%25 yüzdelik (x): 2.0
0.75 quantile (x): 4.0

Kovaryans matrisi:
 [[ 2.5  5. ]
 [ 5.  10. ]]

Korelasyon matrisi:
 [[1. 1.]
 [1. 1.]]

Ne değişti? -> Kovaryans mutlak ölçekten etkilenir; korelasyon -1..1 arası normalize değerdir (burada 1).



---

